# Generated by Django 6.0.2 on 2026-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_comment_author_alter_like_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
