# Generated by Django 6.0.2 on 2026-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_alter_user_avatar_alter_user_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank_score',
            field=models.FloatField(default=0),
        ),
    ]
