# Generated by Django 6.0.2 on 2026-05-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_rank_score'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
