# Generated by Django 6.0.2 on 2026-02-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_nickname_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(default='Не указана', max_length=50, verbose_name='Текущая работа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(default='Новичок', max_length=50, verbose_name='Ранг'),
        ),
    ]
