# Generated by Django 6.0.2 on 2026-04-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_like_post_remove_like_user_remove_post_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
