# Generated by Django 6.0.2 on 2026-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
